### ISSUE TITLE
Add Somneo Logo to HACS integration

### ISSUE THREAD

**Issue by Vato9394** [theneweinstein/somneo#10]
Add an icon in this folder to display it in HACS:
/images/icon.png
/images/icon@2x.png

![icon](https://user-images.githubusercontent.com/24278426/129743009-328dd380-9644-4caf-995a-1b33a2ff223f.png)
![icon@2x](https://user-images.githubusercontent.com/24278426/129743015-0898bebe-5cc2-4636-9520-e48615109d9f.png)

**Comment by Vato9394** [comment]
I am not sure but I think you need to open a pull request on:
https://github.com/home-assistant/brands
and uploads the icons there. (Just helping you out ;) I am not this familiar to github)

**Comment by theneweinstein** [comment]
Thanks, I created a request to add the icons in the brands repository.

**Comment by Vato9394** [comment]
They requested an change on https://github.com/home-assistant/brands.
I approved your logo's since they requested the philips logo, but this is actually an smartsleep integration. hence why they need to use the smartsleep logo.
(https://github.com/home-assistant/brands/pull/2760)
still waiting now for official approval.

**Comment by Vato9394** [comment]
They want the Philips logo added to the repository @ https://github.com/home-assistant/brands
![icon@2x](https://user-images.githubusercontent.com/24278426/130334596-bda0d004-d3da-448e-9d18-1e8f66a4fe98.png)

![icon](https://user-images.githubusercontent.com/24278426/130334572-f485c9c5-bb15-419f-89de-fb3ae683e123.png)
