### ISSUE TITLE
Sensors not working in home assistant 2021.09.0

### ISSUE THREAD

**Issue by Vato9394** [theneweinstein/somneo#12]
the following sensors are not working anymore:
- humidity
- luminance
- noise
- temperature
- next alarm.

Probably has something to do with the changes in sensors that home assistant did recently.
You can still set alarms with the integration.

**Comment by theneweinstein** [comment]
I already updated the master branch to the new native_value property to test it myself, in that case the sensors work. I now created version 2.2.3 with this update. I hope that resolves the problem you have as well.

**Comment by Vato9394** [comment]
Yes, it worked. thanks!
