### ISSUE TITLE
Somneo not starting in HA beta

### ISSUE THREAD

**Issue by confucius78** [theneweinstein/somneo#15]
Hi,

I installed HA 2022-03b and noticed this error in the log:

Logger: homeassistant.util.package
Source: util/package.py:99 
First occurred: February 26, 2022, 11:53:58 AM (12 occurrences) 
Last logged: February 26, 2022, 3:19:30 PM

Unable to install package pysomneo==0.1.12: ERROR: Cannot install pysomneo==0.1.12 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

No reboot possible with this error 😖

**Comment by theneweinstein** [comment]
Hi,

I updated the requirements of pysomneo. The latest version of the integration (2.2.7) gives at least no errors for me.

**Comment by confucius78** [comment]
Great thanks! I have just updated to latest beta, but I presume it'll take a while to get through in the actual HA version. Will keep you posted

**Comment by confucius78** [comment]
So do I need to take some special action in order to get this update local? Sorry for asking, still a complete newbie on python and HA 🤦‍♂️

**Comment by theneweinstein** [comment]
If you are using HACS (https://hacs.xyz/docs/faq/custom_repositories/) you can update via the HACS userinterface in homeassistant. If not, you have to copy the files manually into the custom_components folder in homeassistant (you will need to do that everything you want to update to a new version of the Somneo component).

**Comment by confucius78** [comment]
Yep resolved! Thanks for the pointer, I had in fact manually cloned into the custom components folder per the readme, but this is a lot better! Manmy thanks!
