### ISSUE TITLE
Add slider to control brightness

### ISSUE THREAD

**Issue by jonatino** [theneweinstein/somneo#17]
It would be nice to treat the switch as a dimmer instead of a binary switch.

**Comment by theneweinstein** [comment]
I'm not sure if I understand what you mean. The light of the Somneo is implemented as a light-entity in homeassistant and has a brightness control ('helderheid' in Dutch): 
![image](https://user-images.githubusercontent.com/34983911/179398778-428e3611-f550-4a95-a3ac-246c58a02ce8.png)

**Comment by jonatino** [comment]
@theneweinstein 
![image](https://github.com/theneweinstein/somneo/assets/1808569/a522db9d-e0c3-4d1c-9281-c1eb6b1c3362)

**Comment by jonatino** [comment]
It seems it was recently broken. I had the slider previously up until a recent update.

**Comment by jonatino** [comment]
I'm 99.9% sure this commit broke brightness https://github.com/theneweinstein/somneo/commit/335ce3d4c9f8b8ae2709a4472dcb1f22195a49d7

as downgrading to 5.0.1 fixes the missing brightness slider issue which was released just before this commit was made.

**Comment by theneweinstein** [comment]
It should be fixed now in version 5.1.1.
