### ISSUE TITLE
Cant turn on/off light entity

### ISSUE THREAD

**Issue by jonatino** [theneweinstein/somneo#18]
Hello,

I just installed your extension and every entity/setting works except the main light one. When  I add the light entity, clicking the light on/off does nothing and reverts back to its previous state.

The night light entity works, just not the main light.

See gif: https://dl.dropboxusercontent.com/s/xlvd86cpr1u6qiq/msedge_ChxABD6jd6.mp4

Home Assistant: 2022.7.6
Somneo: latest

**Comment by theneweinstein** [comment]
Hi,

Yes, I see I have the same problem, made some changes in the code and forgot to check this. It should be fixed in v3.0.1 (for me it works at least).

**Comment by jonatino** [comment]
Working with 3.0.1. Issue fixed thank you!
