### ISSUE TITLE
UNIT_PERCENTAGE changed to PERCENTAGE in 115

### ISSUE THREAD

**Issue by Listad79** [theneweinstein/somneo#2]
Hello,

since I found this add-on I am really happy that I can access so many functions of my wakeup light. Today I updated to the latest HA 115 and found a nasty error about an import failure of UNIT_PERCENTAGE. Google informed me that the constant was renamed to PERCENTAGE.
Can you please update the rep so I can enjoy my light in HA again?
[https://github.com/home-assistant/core/issues/40207](https://github.com/home-assistant/core/issues/40207)

**Comment by theneweinstein** [comment]
Hi, I already updated the master branch, but now I see I forgot to update dev to. It should be fixed now.
