### ISSUE TITLE
Getting `upnp/description.xml` no longer works, setup fails

### ISSUE THREAD

**Issue by bramkragten** [theneweinstein/somneo#21]
It seems like the `upnp/description.xml` url is no longer available?

I removed the call to this url from your code, and hard coded the device info, and eventually it worked.

Although I did get a lot of timeouts on the requests, maybe the timeout should be increased, or the requests should not be so close together?

**Comment by theneweinstein** [comment]
Is it still available via de webbrowser: https://ip-adres/upnp/description.xml? I don't have the issue in my installation, perhaps its a problem with never devices, then I'll make a default option in case there is no response from description.xml.

Is the time-out issue related to getting the description, or in general?

**Comment by bramkragten** [comment]
It seems to be available now, I think that the device was rate limited/overloaded or something when I tried to set it up, it seems to work fine now.
