### ISSUE TITLE
Unable to add Somneo Device

### ISSUE THREAD

**Issue by Highsight** [theneweinstein/somneo#24]
Whenever I try and add the device, I get the following error:
![image](https://user-images.githubusercontent.com/1284005/209494684-b0e2c95f-180f-4396-a602-e040f5c9b8b1.png)

I've searched for any log info to help diagnose this further, but can't find anything.  I've confirmed that pysomneo is able to interface with the device just fine in Python, so it appears to be integration itself, or the configuration flow that is causing the issue.  The model is: HF3670/60

**Comment by theneweinstein** [comment]
What did you fill in as a host? It should be an op address (no http or so added to it).

**Comment by Highsight** [comment]
I used the device's IP, with nothing else included.

**Comment by theneweinstein** [comment]
After some googling, it looks like an issue with the XML parser to get the device info of the Somneo. Could you send me the content of https://IP-ADDRESS/upnp/description.xml? Then I can try if I can fix it (or find a work-around).

**Comment by Highsight** [comment]
Ahh, that would make sense.  Here you go!

[description.zip](https://github.com/theneweinstein/somneo/files/10314197/description.zip)

**Comment by Frank071** [comment]
I stumbled upon this same problem, but could not retrieve the file you requested. As it turns out... it can be retrieved via http, but with https I get a 404 error?

**Comment by Highsight** [comment]
> I stumbled upon this same problem, but could not retrieve the file you requested. As it turns out... it can be retrieved via http, but with https I get a 404 error?

Oh, look at that, you're right! I'm unable to access the file if it's https. When I grabbed it, I was just http. If I try https, it returns "{}" instead of the xml. Excellent catch!

**Comment by Frank071** [comment]
I was just planning to create a pull request for pysomneo when I saw that @theneweinstein had already updated the code ;-) Fast work ;-)

**Comment by Highsight** [comment]
Looks like that change got it!  I added it manually, and it seems to connect perfectly now.  Thanks @theneweinstein!

**Comment by theneweinstein** [comment]
Great to hear, I wanted to ask you to test it before I make a new release of it, but it sounds like it works. I'll make a new release with the updated code. Thanks for the help of finding the cause of the issue.
