### ISSUE TITLE
Set AUX via home assistant

### ISSUE THREAD

**Issue by Narta-byte** [theneweinstein/somneo#38]
Hello, I am trying to make the Sonéo into a DIY Bluetooth speaker by using an ESP32. The problem that I am facing is that I have to manually navigate the menu to set it to receive music from AUX. My question is if it's possible to set it to speaker mode via Home Assistant.

**Comment by theneweinstein** [comment]
I don't know, is it possible via the app to select the AUX input (I didn't find the options quickly myself). If it is possible via the app, there should be an API command.

**Comment by Narta-byte** [comment]
Hmm, good question. At a glance, there is no function in the app. It might be a stretch, but this [project](https://github.com/DonkerNet/somneo-client/blob/14d17e946dce30f4ed394153a1ab5d496bc9c07b/src/Donker.Home.Somneo.ApiClient/ISomneoApiClient.cs) seems relevant. At the bottom of the file, there are some functions that sound like they could be related. This could suggest that it might be possible. However, I have not tested it or anything, and it might not even work.

**Comment by theneweinstein** [comment]
That is a great resource! I tested the API commands he sends and you can indeed change to AUX. When I find some time I will add these commands to my python package so it can also be used in HomeAssistant.

**Comment by Narta-byte** [comment]
That sounds awesome!

**Comment by theneweinstein** [comment]
Could you check out the master branch? I added a media_player function. I did some quick test and it seems to be working fine, let me know if there are some bugs left before I create a new release.

**Comment by Narta-byte** [comment]
It seems to be working perfectly!
