### ISSUE TITLE
No way to select specific days

### ISSUE THREAD

**Issue by wleese** [theneweinstein/somneo#42]
When I used SleepMapper to set an alarm, I select certain days for that alarm.
I've just added the integration, but see that for my alarm `select.somneo_wakeup_light_alarm0_days` has value `Unknown`. 

I'd expect to see the day I selected for this alarm, and the ability to change it via this integration.

If there's anything I can do to help debug, let me know :)

**Comment by theneweinstein** [comment]
That is indeed true, as I haven't found a nice way around it. HomeAssistant does not support multi-selects. So if I want to allow all possible combination of days, that would end-up at 127 possibilities per alarm. I choose to support a limited set (weekdays, weekends, everyday and tomorrow) which I think suits most needs. I could add the individual days (so 7 extra possibilities), but adding all combinations I don't see as a good option.

If HomeAssistant supports multi-select entities, I will implement this for the alarm days (see e.g. https://community.home-assistant.io/t/wth-dont-we-have-a-helper-selector-that-allows-multiple-selections/467657).

Maybe you have other ideas how to implement this (without breaking current functionality).

**Comment by wleese** [comment]
Perhaps an addition text input field (accepting day numbers where 0 = monday, or strings such as MON, TUE, all comma seperated) that gets used when the current days value == “custom”?

**Comment by theneweinstein** [comment]
I was thinking something similar yesterday, if I find some time I will try to implement this. Likely it will be a comma-seperated list of days.

**Comment by wleese** [comment]
That’d be awesome. If you manage it and have a digital tip jar, I’d love to leave a tip.

**Comment by theneweinstein** [comment]
I've been playing around with it today and update the master tree. I created a text input where you can list the days (3 letter abbreviations) the alarm should be ringing. This list should be comma-seperated without white-spaces. I did some quick checks at home and it seems to be working. Could you have a look if it works fine like this (download the `master` version)? Let me know if it works, I will create a new release with this function.

**Comment by wleese** [comment]
It looks great!
I tested it by using the entities in HA, checking to see if the changes were reflected in SleepMapper, and then reverse: were changes in SleepMapper reflected in HA. And it works perfectly so far.

Thank you!
