### ISSUE TITLE
Unable to set Sun Theme Duration

### ISSUE THREAD

**Issue by wleese** [theneweinstein/somneo#43]
Am important feature for me was that some days I can set the “Sun Theme” duration to 10 minutes and other days to 30 minutes, depending on how much luxury I want to give myself waking up.

So if I have to get up earlier than usual, I’d set it to 10min, and other days 30min.

I can’t seem to find this feature in this integration.

**Comment by theneweinstein** [comment]
Currently, there is a service that can do this, see: https://github.com/theneweinstein/somneo#services. If you want to have it an entity, you could create in input_number helper and run an automation to call the above mentioned service.

Perhaps in the future I might make it entities.

**Comment by wleese** [comment]
Ah this surprises me a bit. I’d expect all state of an alarm to be exposed in the same way (under the assumption that “Sun theme” is part of am alarms state).

Thanks for the solution, my use case is solved.
