### ISSUE TITLE
light.turn_on / light.turn_off do not support "transition"

### ISSUE THREAD

**Issue by q20** [theneweinstein/somneo#6]
Hi there!

Firstly, thanks for the custom component; it's fantastic being able to control my wake-up light via HA and Homekit.  : )

I have noticed that, when calling the turn light on/off service, transition has no effect; the light will fade on or off in its normal manner (over about 2 seconds), regardless of the transition time called.
Do you think this is something you'd be able to include in your custom component?

Again, thanks so much for your work!  👍 

<img width="503" alt="Untitled 6" src="https://user-images.githubusercontent.com/17024596/102471845-f878db80-4055-11eb-8408-0e1e84ddaa00.png">

**Comment by theneweinstein** [comment]
I had a quick look, and as far as I can see the wake-up light does not have a setting to change the transition time. So I'm afraid I cannot implement this.
