### ISSUE TITLE
access to hass.helpers.discovery is deprecated and will stop working

### ISSUE THREAD

**Issue by DvdEnde** [theneweinstein/somneo#63]
Today I restarted HA and received following warning message in the log:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 1:42:52 PM (1 occurrences)
Last logged: 1:42:52 PM

Detected that custom integration 'philips_somneo' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/philips_somneo/__init__.py, line 40: hass.helpers.discovery.load_platform('sensor', DOMAIN, {}, config), please report it to the author of the 'philips_somneo' custom integration

**Comment by theneweinstein** [comment]
Hi DvdEnde, I think you are posted this in the wrong repository, it seems like it refers to https://github.com/pijiulaoshi/ha_philipssomneo.
