### ISSUE TITLE
light.philipssomneo does not set supported color modes

### ISSUE THREAD

**Issue by DvdEnde** [theneweinstein/somneo#64]
Today I received following warning in logfile when restarting HA:

Logger: homeassistant.components.light
Source: components/light/__init__.py:1266
integration: Light (documentation, issues)
First occurred: 1:43:08 PM (1 occurrences)
Last logged: 1:43:08 PM

light.philipssomneo (<class 'custom_components.philips_somneo.light.SomneoLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'philips_somneo' custom integration

**Comment by theneweinstein** [comment]
Hi DvdEnde, I think you are posted this in the wrong repository, it seems like it refers to https://github.com/pijiulaoshi/ha_philipssomneo.

**Comment by DvdEnde** [comment]
Thank you for your message and apologies for confusion.
kind regards,
Dave
