### ISSUE TITLE
Failed setup, will retry: 3 is not in list

### ISSUE THREAD

**Issue by nfrankel** [theneweinstein/somneo#65]
I've setup the HACS and this integration. The integration finds my Somneo device over the network. Unfortunately, I get the following error message in the UI:

```
Failed setup, will retry: 3 is not in list
```

I've enabled debug logging but I don't know where to check the produced logs.

**Comment by ghostops** [comment]
I have the same issue, this is the error from the Homeassistant logs:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/somneo/__init__.py", line 121, in _async_update
    return await self.hass.async_add_executor_job(self.somneo.fetch_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysomneo/__init__.py", line 174, in fetch_data
    self.data['sunset'] = sunset_to_dict(self.sunset_data, self.dusk_light_themes, self.dusk_sound_themes)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysomneo/util.py", line 51, in sunset_to_dict
    data['curve'] = list(light_curves.keys())[list(light_curves.values()).index(int(sunset_data['ctype']))]
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 3 is not in list
```

**Comment by nfrankel** [comment]
Great! May I ask you how to access the logs?

**Comment by ghostops** [comment]
Here are the official docs: https://www.home-assistant.io/integrations/system_log/

**Comment by nfrankel** [comment]
Thanks a lot!

**Comment by FrankTub** [comment]
I am running into the same issue here. @nfrankel did you succeed in resolving the error?

**Comment by nfrankel** [comment]
Nope :-(

**Comment by theneweinstein** [comment]
Sorry, I haven't had the time to look into this. It seems like something goes wrong when getting the light curves from Somneo. This happens in the pysomneo package, function _get_themes(). Can you check what dusk_light_themes you have? You can do that by going to https://<deviceip>/di/v1/products/1/files/dusklightthemes.

**Comment by FrankTub** [comment]
@theneweinstein , trying out that link on my network does return a `server not found`

**Comment by FrankTub** [comment]
@theneweinstein I realized I was being dumb :) I tried it out and returns an empty json:

![image](https://github.com/user-attachments/assets/790c9d6a-5ef6-4417-91ed-6dae4f17d232)

**Comment by theneweinstein** [comment]
That seems to be fine (like it is with me). Which sunset type is selected in the sleepmapper app? If none is selected (like is example below), please select one and try to add again. I remember with a previous issue (https://github.com/theneweinstein/somneo/issues/53), sometimes the app has not selected a sunset type, which causes an error in homeassistant.
![image](https://github.com/user-attachments/assets/6e3dc761-2c32-4fe4-bd46-06b019f825f6)

**Comment by FrankTub** [comment]
Thanks @theneweinstein that solves the issue, succesfully connected my wake up light now 🙏
