### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by tetsuo55** [theneweinstein/somneo#7]
I have been getting the following error in home assistant since last months update:

SomneoSensor Setup
Error: local variable 'response' referenced before assignment
Fix issue and restart

**Comment by rbouma** [comment]
I got this error also

**Comment by q20** [comment]
Ditto.  : /

Any suggestions?

**Comment by cobra1037** [comment]
home assistant doesnt support this custom component anymore...

**Comment by theneweinstein** [comment]
DarkYodah adjusted the code to deal with this issue (many thanks). Since I cannot reproduce the issue, I cannot check it myself.
